### PR TITLE
Port to Godot 3.0

### PR DESCRIPTION
**Pull request by fleskesvor**
This PR adds many updates from upstream, including the porting to 3.0 done by @StraToN.

For previous discussion, see:

https://github.com/godotengine/escoria/issues/34

### CODE REVIEW

**Comment by nylnook** [comment]
Hi @fleskesvor, 
And thanks a lot for your work! Didn't see that coming at all...

It's probably a great and valuable work as far as I can judge, but I'm not the best one to do the review (I'm more an artist than a developper), and I think we should keep a 2.1.4 version in another branch before to accept your PR, for teaching purposes and waiting for the 3.0 stabilisation...

@punto-, @kdltr, @flossmanualsfr, what do you think ?

**Comment by fleskesvor** [comment]
Hi, @nylnook. It was a pleasure, and a great way for me to become more familiar with both Escoria and Godot 3, but @StraToN should definitely have 99% of the credit. :slightly_smiling_face: 

Yes, I think it's wise to do a proper review, as well as make a legacy 2.1 branch. One of the Godot maintainers made the following suggestion in the discussion I linked to:

> Do like Godot™, branch off to 2.1 and make master compatible with Godot's master branch. Once Godot 3.0 is released, branch off to 3.0 and sync stable stuff from master there every now and then.

Which aligns well with your thoughts.

**Comment by nylnook** [comment]
So, many thanks to @StraToN and every contributor too ;)

I agree this is the best to do, and I'm also intersted if this can also fix Bug #12 as a side effect. 
If @punto- or @kdltr can't do a review, I'll try to, but I will need time and that will be after next week I'm afraid. 

Anyway, that's a nice gift, I promise we will not waste it !

**Comment by fleskesvor** [comment]
No worries. :slightly_smiling_face: If anyone's in a rush to get started, they can just checkout this branch for now.

Yeah, it hopefully solves #12, and it should solve #8 as well, once the 3.0 branch has been merged upstream.

**Comment by nylnook** [comment]
There is no other reviewer around, I saved a 2.1.4 branch... and it looks good to me, so it's merged, waiting for  3.0 stabilization ! thanks a lot for your work !

**Pull request merged**
